// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mfosecdruyjyhxjrhodw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1mb3NlY2RydXlqeWh4anJob2R3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0MjQ1NTAsImV4cCI6MjA2OTAwMDU1MH0.0nBdLxXzwvdGmKqBS8k0JB9G_FUQeyLqEkwmt0ly4jg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});