// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { ENV_CONFIG } from '@/lib/env-config';

const SUPABASE_URL = ENV_CONFIG.SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = ENV_CONFIG.SUPABASE_ANON_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});