name: Supabase Migrations

on:
  push:
    branches: [main]
    paths:
      - 'supabase/migrations/**'
  workflow_dispatch:

jobs:
  run-migrations:
    runs-on: ubuntu-latest
    environment: production
    
    steps:
      - uses: actions/checkout@v5
      
      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest
      
      - name: Run database migrations
        run: |
          supabase db push --project-ref majqoqagohicjigmsilu
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      
      - name: Notify migration success
        if: success()
        run: echo "✅ Database migrations applied successfully!"
